
default: &default
  adapter: postgresql
  username: <%= ENV.fetch("POSTGRES_USER")%>
  password: <%= ENV.fetch("POSTGRES_PASSWORD")%>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: react_rails_app_development

test:
  <<: *default
  database: react_rails_app_test

production:
  <<: *default
  database: react_rails_app_production
